require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - bin/yarn
    - node_modules/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "db/schema.rb"
    - "config/initializers/rails_admin.rb"
RSpec/ExampleLength:
  Max: 30
RSpec/MultipleExpectations:
  Max: 10
RSpec/DescribedClass:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
