require:
  - rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/node-sass/src/libsass/contrib/libsass.spec
    - node_modules/node-sass/src/libsass/extconf.rb
    - bin/yarn

Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "db/schema.rb"
    - "config/initializers/rails_admin.rb"
