AllCops:
  Excludes:
    - db/schema.rb
    - node_modules/node-sass/src/libsass/contrib/libsass.spec
    - node_modules/node-sass/src/libsass/extconf.rb
    - bin/yarn

Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
