language: ruby
rvm:
  - 2.5.1

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - sudo apt-get -y install libpq-dev

cache:
  yarn: true

install:
  - yarn
  - gem install bundler -v '1.17.3'
  - bundle install

script: rspec spec
# should be done after creating heroku account
# deploy:
#   provider: heroku
#   run: "rake db:migrate"
#   api_key:
#     secure: "YOUR ENCRYPTED API KEY"
